### ISSUE TITLE
Sentry Semantic Conventions v0

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-conventions#1]
```[tasklist]
### Tasks
- [x] Create JSONSchema for conventions schema
- [x] Port over https://develop.sentry.dev/sdk/performance/span-data-conventions/ into repo
- [x] Port over https://develop.sentry.dev/sdk/performance/span-operations/
- [x] Attempt to audit SDKs for what values they set in span data/breadcrumb data
```
